create or replace TABLE GX_GUARDIAN.CONFIG.GXTASK (
	COMPONENT_ID VARCHAR(16777216) NOT NULL,
	PASSIVE_POLICY_ID VARCHAR(16777216) NOT NULL,
	FULL_DESCRIPTOR VARCHAR(16777216) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
	primary key (COMPONENT_ID)
);